/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MtrIndexRouteImport } from './routes/mtr/index'
import { Route as BusIndexRouteImport } from './routes/bus/index'
import { Route as MtrLineDirRouteImport } from './routes/mtr/$line.$dir'
import { Route as BusCoRouteBoundServiceRouteImport } from './routes/bus/$co.$route.$bound.$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MtrIndexRoute = MtrIndexRouteImport.update({
  id: '/mtr/',
  path: '/mtr/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusIndexRoute = BusIndexRouteImport.update({
  id: '/bus/',
  path: '/bus/',
  getParentRoute: () => rootRouteImport,
} as any)
const MtrLineDirRoute = MtrLineDirRouteImport.update({
  id: '/mtr/$line/$dir',
  path: '/mtr/$line/$dir',
  getParentRoute: () => rootRouteImport,
} as any)
const BusCoRouteBoundServiceRoute = BusCoRouteBoundServiceRouteImport.update({
  id: '/bus/$co/$route/$bound/$service',
  path: '/bus/$co/$route/$bound/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus/': typeof BusIndexRoute
  '/mtr/': typeof MtrIndexRoute
  '/mtr/$line/$dir': typeof MtrLineDirRoute
  '/bus/$co/$route/$bound/$service': typeof BusCoRouteBoundServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusIndexRoute
  '/mtr': typeof MtrIndexRoute
  '/mtr/$line/$dir': typeof MtrLineDirRoute
  '/bus/$co/$route/$bound/$service': typeof BusCoRouteBoundServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus/': typeof BusIndexRoute
  '/mtr/': typeof MtrIndexRoute
  '/mtr/$line/$dir': typeof MtrLineDirRoute
  '/bus/$co/$route/$bound/$service': typeof BusCoRouteBoundServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus/'
    | '/mtr/'
    | '/mtr/$line/$dir'
    | '/bus/$co/$route/$bound/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/mtr'
    | '/mtr/$line/$dir'
    | '/bus/$co/$route/$bound/$service'
  id:
    | '__root__'
    | '/'
    | '/bus/'
    | '/mtr/'
    | '/mtr/$line/$dir'
    | '/bus/$co/$route/$bound/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusIndexRoute: typeof BusIndexRoute
  MtrIndexRoute: typeof MtrIndexRoute
  MtrLineDirRoute: typeof MtrLineDirRoute
  BusCoRouteBoundServiceRoute: typeof BusCoRouteBoundServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtr/': {
      id: '/mtr/'
      path: '/mtr'
      fullPath: '/mtr/'
      preLoaderRoute: typeof MtrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus/': {
      id: '/bus/'
      path: '/bus'
      fullPath: '/bus/'
      preLoaderRoute: typeof BusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtr/$line/$dir': {
      id: '/mtr/$line/$dir'
      path: '/mtr/$line/$dir'
      fullPath: '/mtr/$line/$dir'
      preLoaderRoute: typeof MtrLineDirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus/$co/$route/$bound/$service': {
      id: '/bus/$co/$route/$bound/$service'
      path: '/bus/$co/$route/$bound/$service'
      fullPath: '/bus/$co/$route/$bound/$service'
      preLoaderRoute: typeof BusCoRouteBoundServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusIndexRoute: BusIndexRoute,
  MtrIndexRoute: MtrIndexRoute,
  MtrLineDirRoute: MtrLineDirRoute,
  BusCoRouteBoundServiceRoute: BusCoRouteBoundServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
