/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MtrIndexRouteImport } from './routes/mtr/index'
import { Route as BusIndexRouteImport } from './routes/bus/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MtrIndexRoute = MtrIndexRouteImport.update({
  id: '/mtr/',
  path: '/mtr/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusIndexRoute = BusIndexRouteImport.update({
  id: '/bus/',
  path: '/bus/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus/': typeof BusIndexRoute
  '/mtr/': typeof MtrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusIndexRoute
  '/mtr': typeof MtrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus/': typeof BusIndexRoute
  '/mtr/': typeof MtrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bus/' | '/mtr/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bus' | '/mtr'
  id: '__root__' | '/' | '/bus/' | '/mtr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusIndexRoute: typeof BusIndexRoute
  MtrIndexRoute: typeof MtrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtr/': {
      id: '/mtr/'
      path: '/mtr'
      fullPath: '/mtr/'
      preLoaderRoute: typeof MtrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus/': {
      id: '/bus/'
      path: '/bus'
      fullPath: '/bus/'
      preLoaderRoute: typeof BusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusIndexRoute: BusIndexRoute,
  MtrIndexRoute: MtrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
